web:
  build: web
  environment:
    VIRTUAL_HOST: "*/*"
webapi:
  build: webapi
  environment:
    VIRTUAL_HOST: "*/api, */api/*"
  links:
    - redis
redis:
    image: redis:latest
    ports:
        - "6379"
lb:
  image: tutum/haproxy
  links:
    - web
    - webapi
  ports:
    - "80:80"