web:
  build: web
  environment:
    VIRTUAL_HOST: "*/*"
webapi:
  build: webapi
  environment:
    VIRTUAL_HOST: "*/api, */api/*"
    ASPNET_ENV: Development
  links:
    - redis
redis:
  image: anapsix/webdis
  environment:
    LOCAL_REDIS: true
  ports:
    - "7379:7379"
lb:
  image: tutum/haproxy
  links:
    - web
    - webapi
  ports:
    - "80:80"